### ISSUE TITLE
Possible Pagination Example Improvement

### ISSUE THREAD

**Issue by janxious** [simplebits/Pears#5]
There doesn't seem to be a way to submit changes or anything to the Pears example site. I was thinking something like this for pagination:

``` html
<nav role="page">
    <ul>
        <li class="page-prev"><a href="#">← Prev</a></li>
        <li><a href="#">1</a></li>
        <li><a href="#">2</a></li>
        <li><a href="#">3</a></li>
        <li class="current">4</li>
        <li class="page-next"><a href="#">Next →</a></li>
    </ul>
</nav>
```

``` CSS
nav[role=page] ul {
    text-align: center;
    }
nav[role=page] li {
    display: inline;
    margin: 0 4px 0 0;
    }
nav[role=page] a {
    padding: 3px 8px;
    font-size: 14px;
    font-weight: bold;
    border: 1px solid #ddd;
  background: #fff;
    border-radius: 4px;
    }
nav[role=page] a:hover,
nav[role=page] a:focus {
    background: #f0f0f0;
    border-color: #ccc;
    }
nav[role=page] a:active {
    background: #fff;
    border-color: #ddd;
    }
nav[role=page] .current {
    font-weight: bold;
    padding: 3px 3px;
    }
```
